name: Actualizar Horario

on:
  schedule:
    - cron: '*/30 * * * *' # Corre cada 30 minutos
  workflow_dispatch:      # Permite correrlo manualmente

permissions:
  contents: write         # Permiso para que el bot edite el README

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar requests
        run: pip install requests

      - name: Ejecutar script
        run: python actualizar.py

      - name: Guardar cambios
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Actualización automática de cupos" || exit 0
          git push
